# Используйте образ Node.js
FROM node:20.11.1

# Установите рабочую директорию
WORKDIR /usr/src/app

# Откройте порт для React development server
EXPOSE 3002

# Команда-заглушка для оставания контейнера в рабочем состоянии
CMD ["tail", "-f", "/dev/null"]