version: "3.8"

include:
  - ../../backend/docker/docker-compose.yml
  - ../../frontend/docker/docker-compose.yml

services:
  web:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/templates
    ports:
      - "3000:80"
    environment:
      - NGINX_PORT=80
